# Generated by Django 2.2 on 2021-12-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0003_aboutmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('period', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='events')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='projects')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='image',
            field=models.ImageField(upload_to='about'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='presiImage',
            field=models.ImageField(default='', upload_to='about'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='sgImage',
            field=models.ImageField(default='', upload_to='about'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='vpImage',
            field=models.ImageField(default='', upload_to='about'),
        ),
    ]
