# Generated by Django 2.2 on 2021-12-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0004_auto_20211220_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.TextField(max_length=50)),
                ('intro', models.TextField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='about')),
            ],
        ),
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=500)),
                ('intro1', models.TextField(max_length=100)),
                ('intro2', models.TextField(max_length=100)),
                ('memberCount', models.TextField(max_length=20)),
                ('branchCount', models.TextField(max_length=20)),
                ('quaterCount', models.TextField(max_length=20)),
                ('homeImage', models.ImageField(upload_to='projects')),
                ('aboutImage', models.ImageField(default='', upload_to='about')),
            ],
        ),
    ]
