# Generated by Django 2.2 on 2021-12-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0005_executivemodel_homemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='aboutImage',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='homeImage',
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='banner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='intro1',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='intro2',
            field=models.TextField(max_length=50),
        ),
    ]
