# Generated by Django 2.2 on 2021-12-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0006_auto_20211220_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='branchCount',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='memberCount',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='quaterCount',
        ),
    ]
