# Generated by Django 2.2 on 2021-12-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0007_auto_20211220_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeModel',
        ),
        migrations.AlterField(
            model_name='executivemodel',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
