# Generated by Django 2.2 on 2022-02-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0008_auto_20211220_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('subject', models.TextField(default='', max_length=1000)),
                ('message', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
