# Generated by Django 5.1 on 2024-08-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0010_staticcontactmodel_alter_aboutmodel_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaticContactModel',
            new_name='StaticModel',
        ),
    ]
