# Generated by Django 5.1 on 2024-08-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0011_rename_staticcontactmodel_staticmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaticModel',
            new_name='AddressModel',
        ),
    ]
