# Generated by Django 5.1 on 2024-08-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0012_rename_staticmodel_addressmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='quater',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
