# Generated by Django 5.1 on 2024-08-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0013_contactmodel_phone_contactmodel_quater_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='subject',
        ),
    ]
