# Generated by Django 5.1 on 2024-08-27 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0014_remove_contactmodel_message_remove_contactmodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuaterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('head', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('meeting_location', models.CharField(default='', max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='bamedcacontent.branchmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='AddressModel',
        ),
    ]
