# Generated by Django 5.1 on 2024-08-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0017_rename_contactmessage_messagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageModel',
        ),
    ]
