# Generated by Django 5.1 on 2024-08-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0018_delete_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quatermodel',
            name='image',
            field=models.ImageField(default='', upload_to='quarter'),
        ),
    ]
