# Generated by Django 5.1 on 2024-08-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0021_alter_aboutmodel_paragraph1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='paragraph1',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='paragraph2',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='paragraph3',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='paragraph1',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='paragraph2',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='paragraph3',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='paragraph1',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='paragraph2',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='paragraph3',
            field=models.TextField(max_length=1000),
        ),
    ]
