# Generated by Django 5.1 on 2024-10-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0022_alter_aboutmodel_paragraph1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.IntegerField(default=0)),
                ('branches', models.IntegerField(default=0)),
                ('quarters', models.IntegerField(default=0)),
            ],
        ),
    ]
