# Generated by Django 5.1 on 2024-10-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0023_countermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intro1', models.CharField(max_length=200)),
                ('Intro2', models.CharField(max_length=200)),
                ('Intro3', models.CharField(max_length=200)),
                ('whyBelong', models.TextField(max_length=1000)),
                ('Reason1', models.CharField(max_length=200)),
                ('Description1', models.TextField(max_length=1000)),
                ('Reason2', models.CharField(max_length=200)),
                ('Description2', models.TextField(max_length=1000)),
                ('Reason3', models.CharField(max_length=200)),
                ('Description3', models.TextField(max_length=1000)),
            ],
        ),
    ]
