# Generated by Django 5.1 on 2024-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0024_homemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intro1', models.CharField(max_length=200)),
                ('Intro2', models.CharField(max_length=200)),
                ('Intro3', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='Intro1',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='Intro2',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='Intro3',
        ),
    ]
