# Generated by Django 5.1 on 2024-10-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0025_intromodel_remove_homemodel_intro1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntroModel',
        ),
        migrations.AddField(
            model_name='homemodel',
            name='Intro1',
            field=models.CharField(default='hey', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemodel',
            name='Intro2',
            field=models.CharField(default='hey', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemodel',
            name='Intro3',
            field=models.CharField(default='hey', max_length=1000),
            preserve_default=False,
        ),
    ]
