# Generated by Django 5.1 on 2025-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0026_delete_intromodel_homemodel_intro1_homemodel_intro2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='aboutintro',
            field=models.TextField(default='BAMEDCA is an independent, non-profit, and community-based organization dedicated to fostering the holistic transformation of the Bamendankwe community. With our head office located in Bamendankwe, Mezam Division, North-West Cameroon, and branches across the country and in the diaspora, we are committed to addressing the developmental challenges facing our community while preserving and promoting our rich culture and traditions.', max_length=1000),
            preserve_default=False,
        ),
    ]
