# Generated by Django 5.1 on 2025-07-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0027_homemodel_aboutintro'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='WhatWeDo1',
            field=models.TextField(default='nothing', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='WhatWeDo2',
            field=models.TextField(default='nothing', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='WhatWeDo3',
            field=models.TextField(default='nothing', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='WhatWeDo4',
            field=models.TextField(default='nothing', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='WhatWeDo5',
            field=models.TextField(default='nothing', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='WhatWeDo6',
            field=models.TextField(default='nothing', max_length=1000),
            preserve_default=False,
        ),
    ]
