# Generated by Django 5.1 on 2025-07-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0028_aboutmodel_whatwedo1_aboutmodel_whatwedo2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeDoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WhatWeDo1', models.TextField(max_length=1000)),
                ('WhatWeDo2', models.TextField(max_length=1000)),
                ('WhatWeDo3', models.TextField(max_length=1000)),
                ('WhatWeDo4', models.TextField(max_length=1000)),
                ('WhatWeDo5', models.TextField(max_length=1000)),
                ('WhatWeDo6', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='WhatWeDo1',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='WhatWeDo2',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='WhatWeDo3',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='WhatWeDo4',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='WhatWeDo5',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='WhatWeDo6',
        ),
    ]
