# Generated by Django 5.1 on 2025-07-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0029_whatwedomodel_remove_aboutmodel_whatwedo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedomodel',
            name='name',
            field=models.TextField(default='What We Do', max_length=20),
            preserve_default=False,
        ),
    ]
