# Generated by Django 5.1 on 2025-07-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0030_whatwedomodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchmodel',
            old_name='quater',
            new_name='quarter',
        ),
    ]
