# Generated by Django 5.1 on 2025-07-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bamedcacontent', '0031_rename_quater_branchmodel_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='quater',
        ),
    ]
